### ISSUE TITLE
[S1-PBI9] CRUD SPV 

### ISSUE THREAD

**Issue by ahdanihimam** [SI-RPL-2021/FUEL-TRACKER#9]
saya sebagai Administrator dapat menambahkan, mengubah, menghapus, view data supervisor (CRUD) agar dapat mengelola data supervisor. 
![Tabel Supervisor](https://user-images.githubusercontent.com/71952197/112620467-25aa0680-8e5b-11eb-9bd3-01c1dfa53d04.png)
![Tabel Data Supervisor (2)](https://user-images.githubusercontent.com/71952197/112620473-26db3380-8e5b-11eb-8f09-f06b37bc878d.png)

**Comment by riskiawp** [comment]
Edit view tabel
